import { Google_Sans } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/Header";
import FooterComponent from "@/components/Footer";

const googleSans = Google_Sans({
  variable: "--font-google-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${googleSans.variable} antialiased`}>
        <HeaderComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
